services:
  caddy:
    build:
      context: caddy
    image: caddy:${CADDY_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_cdcs_caddy
    restart: always
    ports:
      - "${CADDY_PORT_80}:80"
      - "${CADDY_PORT_443}:443"
    depends_on:
      - cdcs
    volumes:
      - cdcs_socket:/tmp/curator/
      - cdcs_static:/srv/curator_static
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/certs:/etc/caddy/certs:ro
      - caddy_data:/data
      - caddy_config:/config
      - ./cdcs/nx-data:/srv/nx-data:ro
      - ./cdcs/nx-instrument-data:/srv/nx-instrument-data:ro
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_cdcs_postgres
    restart: always
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
  redis:
    image: redis:${REDIS_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_cdcs_redis
    command: redis-server --requirepass ${REDIS_PASS}
    restart: always
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - redis_data:/data
  cdcs:
    build:
      context: ..
      dockerfile: .dev-deployment/Dockerfile
    image: nexuslims-cdcs:${IMAGE_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_cdcs
    restart: always
    depends_on:
      - redis
      - postgres
    extra_hosts:
      # allows access from Celery processes to caddy reverse proxy network
      # (the query exporter was failing without this addition)
      - "nexuslims-dev.localhost:host-gateway"
    volumes:
      - cdcs_media:/srv/curator/media
      - cdcs_socket:/tmp/curator/
      - cdcs_static:/srv/curator/static.prod
      # Uncomment to mount additional settings file
      - ./cdcs/${SETTINGS}.py:/srv/curator/${PROJECT_NAME}/${SETTINGS}.py
      # Mount CDCS configuration and assets folder
      - ./cdcs:/srv/curator/cdcs_config:ro
      # Mount Caddy's root CA certificate for SSL verification
      - ./caddy/certs/ca.crt:/etc/ssl/certs/caddy-root-ca.crt:ro
    environment:
      - DJANGO_SETTINGS_MODULE=${PROJECT_NAME}.${SETTINGS}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - SERVER_URI=${SERVER_URI}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - SERVER_NAME=${SERVER_NAME:-}
      # Use Caddy's root CA certificate for development
      # (allows celery and other requests to verify SSL requests against
      # Caddy's self-signed cert)
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/caddy-root-ca.crt
      - CURL_CA_BUNDLE=/etc/ssl/certs/caddy-root-ca.crt
      - MONGO_HOST=${COMPOSE_PROJECT_NAME}_cdcs_mongo
      - MONGO_PORT=27017
      - MONGO_DB=${MONGO_DB}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - POSTGRES_HOST=${COMPOSE_PROJECT_NAME}_cdcs_postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - REDIS_HOST=${COMPOSE_PROJECT_NAME}_cdcs_redis
      - REDIS_PORT=6379
      - REDIS_PASS=${REDIS_PASS}
    env_file:
      - ./saml2/.env
      - ./handle/.env
      - ./extra/.env
    command:
      - ${PROJECT_NAME}
      - ${WEB_SERVER:-uwsgi}

volumes:
  postgres_data:
  redis_data:
  cdcs_media:
  cdcs_socket:
  cdcs_static:
  caddy_data:
  caddy_config:
